spring.application.name=domain-blocker-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/domain_db
spring.datasource.username=postgres
spring.datasource.password=1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


ssh.host=192.168.56.101
ssh.user=ulak
ssh.password=22102380

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false
