spring.application.name=domain-blocker-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/domain_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


ssh.host=192.168.56.101
ssh.user=ulak
ssh.password=22102380



spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Veritaban? ?emas?n? art?k Liquibase yönetecek
spring.jpa.hibernate.ddl-auto=none

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
#bilgilerin gözükebilmesi için izin
management.info.env.enabled=true 

info.app.name=Domain Blocker Backend
info.app.description=Uzak sunucu uzerinden domain engelleme projesi
info.app.version=1.0.0
info.app.stajyer=Zeynep
